# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

build:
  correctness:
    build:
      image: typedb-ubuntu-22.04
      command: |
        bazel build //...
        bazel test $(bazel query 'kind(checkstyle_test, //... except tool/ide/...)') || exit 1
    rust-ide-sync:
      image: typedb-ubuntu-22.04
      command: |
        library/crates/get_cargo.sh
        export PATH=$PATH:$PWD
        cd tool/ide/test/
        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=streamed || exit 1
        tool/ide/rust/sync.sh
        cargo generate-lockfile --quiet && echo SUCCESS
    deploy-maven-snapshot:
      filter:
        owner: typedb
#        branch: [ master, development ]
      image: typedb-ubuntu-22.04
      dependencies: [ build ]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_TYPEDB_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_TYPEDB_PASSWORD
        bazel run //tool/bazelinstall:remote_cache_setup.sh
        bazel run --define version=$(git rev-parse HEAD) //common/java:deploy-maven -- snapshot
    sync-dependencies:
      image: typedb-ubuntu-22.04
      filter:
        owner: typedb
        branch: [master, development]
      dependencies: [build]
      command: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @typedb_dependencies//tool/sync:dependencies -- --source ${FACTORY_REPO}@${FACTORY_COMMIT}
